export const style = {
  position: "absolute",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: "75%",
  height: "80%",
  backgroundColor: "white",
  border: "2px solid #000",
  boxShadow: 24,
  overflowY: "auto",
  overflowX: "hidden",
  borderRadius: "10px",
  fontSize: "20px",
  padding: "25px 50px",
};
